rem
	BlitzMax Source Generated by Scyndi
	Please read the original coder's documentation about the
	Copyright notices and under which terms this code may
	be distributed (if it may be distributed at al)
end rem


strict

function CRASH(A) 
	error("Scyndi-RuntimeError:\t"..A) 
end
	
	function scynipairs(a)
		if type(a)!="table" then CRASH("Table expected for iteration!") end
		i=0
		t={}
		for j=0,#a do t[#t+1]=a[j] end
		return function()
			i=i+1
			return i-1,t[i]
		end
	end
	
	func i2scyntab(a)
		if type(a)!="table" then CRASH("Table expected for iteration!") end
		ret = {}
		for i=1,#a do ret[i-1]=a[i] end
		return ret
	end
	


-- Module: SYSTEM
-- Code generated by Scyndi




-- Global Variables (and constants)


-- Translated functions

function SCYNDI_PRG_SYSTEM_VOID_WRITE ( SCYNDI_ARGUMENT_T  )
	for i,tx in scynipairs(SCYNDI_ARGUMENT_T) do
		io.write(tx)
		if i~=#SCYNDI_ARGUMENT_T then io.write(" ") end
	end

end

function SCYNDI_PRG_SYSTEM_VOID_WRITELN ( SCYNDI_ARGUMENT_T  )
	for i,tx in scynipairs(SCYNDI_ARGUMENT_T) do
		io.write(tx)
		if i~=#SCYNDI_ARGUMENT_T then io.write(" ") end
		io.write(string.char(10))
	end

end




-- End module: HELLOWORLD

-- ************
-- MAIN PROGRAM
-- ************
-- Code generated by Scyndi




-- Global Variables (and constants)


-- Translated functions

function SCYNDI_PRG_HELLOWORLD_VOID_MAIN (  )
	SCYNDI_PRG_SYSTEM_VOID_WRITELN({ [0] = "Hello, world!" })
end





-- Call main
SCYNDI_PRG_HELLOWORLD_VOID_MAIN()
